sonar.projectKey=ChandrikaJain26_python-devops-app
sonar.organization=chandrikajain26
sonar.host.url=https://sonarcloud.io

sonar.sources=app
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=unit-report.xml
