apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-devops-app
  template:
    metadata:
      labels:
        app: python-devops-app
    spec:
      imagePullSecrets:
        - name: nexus-docker-secret
      containers:
      - name: python-devops-app
        image: 193913969706.dkr.ecr.ap-south-1.amazonaws.com/python-devops-app:20
        ports:
        - containerPort: 8080
